2020-02-27 09:55:24,159 - -----------------------------------------------------------------
2020-02-27 09:55:24,159 - Job Controller starting...
2020-02-27 09:55:24,162 - Job Controller is Active
2020-02-27 09:55:24,163 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 09:55:24,164 - Job Controller stopping - lost connection to remote server
2020-02-27 09:55:24,164 - -----------------------------------------------------------------
2020-02-27 09:56:06,708 - -----------------------------------------------------------------
2020-02-27 09:56:06,708 - Job Controller starting...
2020-02-27 09:56:06,711 - Job Controller is Active
2020-02-27 09:56:06,714 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 09:56:06,714 - Job Controller stopping - lost connection to remote server
2020-02-27 09:56:06,714 - -----------------------------------------------------------------
2020-02-27 09:57:06,936 - -----------------------------------------------------------------
2020-02-27 09:57:06,937 - Job Controller starting...
2020-02-27 09:57:06,939 - Job Controller is Active
2020-02-27 09:57:06,941 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 09:57:06,941 - Job Controller stopping - lost connection to remote server
2020-02-27 09:57:06,941 - -----------------------------------------------------------------
2020-02-27 09:57:46,316 - -----------------------------------------------------------------
2020-02-27 09:57:46,316 - Job Controller starting...
2020-02-27 09:57:46,318 - Job Controller is Active
2020-02-27 09:57:47,105 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 846, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2020-02-27 09:57:47,106 - Job Controller stopping - lost connection to remote server
2020-02-27 09:57:47,107 - -----------------------------------------------------------------
2020-02-27 09:58:33,293 - -----------------------------------------------------------------
2020-02-27 09:58:33,293 - Job Controller starting...
2020-02-27 09:58:33,296 - Job Controller is Active
2020-02-27 09:58:33,971 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 846, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2020-02-27 09:58:33,972 - Job Controller stopping - lost connection to remote server
2020-02-27 09:58:33,972 - -----------------------------------------------------------------
2020-02-27 10:01:25,334 - -----------------------------------------------------------------
2020-02-27 10:01:25,334 - Job Controller starting...
2020-02-27 10:01:25,337 - Job Controller is Active
2020-02-27 10:01:26,205 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 846, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2020-02-27 10:01:26,207 - Job Controller stopping - lost connection to remote server
2020-02-27 10:01:26,207 - -----------------------------------------------------------------
2020-02-27 10:01:45,971 - -----------------------------------------------------------------
2020-02-27 10:01:45,971 - Job Controller starting...
2020-02-27 10:01:45,974 - Job Controller is Active
2020-02-27 10:01:45,976 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 10:01:45,977 - Job Controller stopping - lost connection to remote server
2020-02-27 10:01:45,977 - -----------------------------------------------------------------
2020-02-27 10:02:46,149 - -----------------------------------------------------------------
2020-02-27 10:02:46,149 - Job Controller starting...
2020-02-27 10:02:46,152 - Job Controller is Active
2020-02-27 10:02:46,153 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 10:02:46,153 - Job Controller stopping - lost connection to remote server
2020-02-27 10:02:46,153 - -----------------------------------------------------------------
2020-02-27 10:03:03,520 - -----------------------------------------------------------------
2020-02-27 10:03:03,521 - Job Controller starting...
2020-02-27 10:03:03,523 - Job Controller is Active
2020-02-27 10:03:03,524 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 10:03:03,524 - Job Controller stopping - lost connection to remote server
2020-02-27 10:03:03,524 - -----------------------------------------------------------------
2020-02-27 10:04:03,709 - -----------------------------------------------------------------
2020-02-27 10:04:03,709 - Job Controller starting...
2020-02-27 10:04:03,712 - Job Controller is Active
2020-02-27 10:04:03,713 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 10:04:03,714 - Job Controller stopping - lost connection to remote server
2020-02-27 10:04:03,714 - -----------------------------------------------------------------
2020-02-27 10:04:39,826 - -----------------------------------------------------------------
2020-02-27 10:04:39,826 - Job Controller starting...
2020-02-27 10:04:39,828 - Job Controller is Active
2020-02-27 10:04:39,829 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 10:04:39,830 - Job Controller stopping - lost connection to remote server
2020-02-27 10:04:39,830 - -----------------------------------------------------------------
2020-02-27 10:11:18,427 - -----------------------------------------------------------------
2020-02-27 10:11:18,427 - Job Controller starting...
2020-02-27 10:11:18,429 - Job Controller is Active
2020-02-27 10:11:18,430 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 10:11:18,431 - Job Controller stopping - lost connection to remote server
2020-02-27 10:11:18,431 - -----------------------------------------------------------------
2020-02-27 10:12:48,652 - -----------------------------------------------------------------
2020-02-27 10:12:48,652 - Job Controller starting...
2020-02-27 10:12:48,655 - Job Controller is Active
2020-02-27 10:12:48,656 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 10:12:48,656 - Job Controller stopping - lost connection to remote server
2020-02-27 10:12:48,656 - -----------------------------------------------------------------
2020-02-27 10:13:11,669 - -----------------------------------------------------------------
2020-02-27 10:13:11,669 - Job Controller starting...
2020-02-27 10:13:11,672 - Job Controller is Active
2020-02-27 10:13:11,673 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 10:13:11,674 - Job Controller stopping - lost connection to remote server
2020-02-27 10:13:11,674 - -----------------------------------------------------------------
2020-02-27 10:27:08,963 - -----------------------------------------------------------------
2020-02-27 10:27:08,963 - Job Controller starting...
2020-02-27 10:27:08,965 - Job Controller is Active
2020-02-27 10:27:08,966 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedOK('code = 1000 (OK), reason = Bye.')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = Bye.
2020-02-27 10:27:08,967 - Job Controller stopping - lost connection to remote server
2020-02-27 10:27:08,967 - -----------------------------------------------------------------
2020-02-27 10:28:09,143 - -----------------------------------------------------------------
2020-02-27 10:28:09,144 - Job Controller starting...
2020-02-27 10:28:09,146 - Job Controller is Active
2020-02-27 10:28:09,147 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedOK('code = 1000 (OK), reason = Bye.')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = Bye.
2020-02-27 10:28:09,148 - Job Controller stopping - lost connection to remote server
2020-02-27 10:28:09,148 - -----------------------------------------------------------------
2020-02-27 10:29:09,353 - -----------------------------------------------------------------
2020-02-27 10:29:09,353 - Job Controller starting...
2020-02-27 10:29:09,357 - Job Controller is Active
2020-02-27 10:29:09,358 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedOK('code = 1000 (OK), reason = Bye.')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = Bye.
2020-02-27 10:29:09,359 - Job Controller stopping - lost connection to remote server
2020-02-27 10:29:09,359 - -----------------------------------------------------------------
2020-02-27 10:30:09,576 - -----------------------------------------------------------------
2020-02-27 10:30:09,576 - Job Controller starting...
2020-02-27 10:30:09,579 - Job Controller is Active
2020-02-27 10:30:09,580 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedOK('code = 1000 (OK), reason = Bye.')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = Bye.
2020-02-27 10:30:09,581 - Job Controller stopping - lost connection to remote server
2020-02-27 10:30:09,581 - -----------------------------------------------------------------
2020-02-27 10:31:09,750 - -----------------------------------------------------------------
2020-02-27 10:31:09,750 - Job Controller starting...
2020-02-27 10:31:09,752 - Job Controller is Active
2020-02-27 10:31:09,754 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedOK('code = 1000 (OK), reason = Bye.')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = Bye.
2020-02-27 10:31:09,754 - Job Controller stopping - lost connection to remote server
2020-02-27 10:31:09,754 - -----------------------------------------------------------------
2020-02-27 10:32:09,919 - -----------------------------------------------------------------
2020-02-27 10:32:09,919 - Job Controller starting...
2020-02-27 10:32:09,921 - Job Controller is Active
2020-02-27 10:32:09,923 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedOK('code = 1000 (OK), reason = Bye.')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = Bye.
2020-02-27 10:32:09,923 - Job Controller stopping - lost connection to remote server
2020-02-27 10:32:09,923 - -----------------------------------------------------------------
2020-02-27 10:35:48,173 - -----------------------------------------------------------------
2020-02-27 10:35:48,175 - Job Controller starting...
2020-02-27 10:35:48,178 - Job Controller is Active
2020-02-27 10:35:49,041 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedOK('code = 1000 (OK), reason = Bye.')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = Bye.
2020-02-27 10:35:49,042 - Job Controller stopping - lost connection to remote server
2020-02-27 10:35:49,043 - -----------------------------------------------------------------
2020-02-27 10:35:55,698 - -----------------------------------------------------------------
2020-02-27 10:35:55,698 - Job Controller starting...
2020-02-27 10:35:55,701 - Job Controller is Active
2020-02-27 10:36:15,716 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedOK('code = 1000 (OK), reason = Bye.')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = Bye.
2020-02-27 10:36:15,717 - Job Controller stopping - lost connection to remote server
2020-02-27 10:36:15,717 - -----------------------------------------------------------------
2020-02-27 10:52:57,103 - -----------------------------------------------------------------
2020-02-27 10:52:57,103 - Job Controller starting...
2020-02-27 10:52:57,108 - Job Controller is Active
2020-02-27 10:52:57,968 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedOK('code = 1000 (OK), reason = Bye.')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = Bye.
2020-02-27 10:52:57,969 - Job Controller stopping - lost connection to remote server
2020-02-27 10:52:57,969 - -----------------------------------------------------------------
2020-02-27 10:53:02,306 - -----------------------------------------------------------------
2020-02-27 10:53:02,306 - Job Controller starting...
2020-02-27 10:53:02,309 - Job Controller is Active
2020-02-27 10:53:31,811 - -----------------------------------------------------------------
2020-02-27 10:53:31,811 - Job Controller starting...
2020-02-27 10:53:31,814 - Job Controller is Active
2020-02-27 10:53:31,816 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=ConnectionClosedOK('code = 1000 (OK), reason = Bye.')>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 359, in recv_handler
    message = await self.sock.recv()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lewis/Projects/gwcloud_job_client/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = Bye.
2020-02-27 10:53:31,817 - Job Controller stopping - lost connection to remote server
2020-02-27 10:53:31,817 - -----------------------------------------------------------------
2020-02-27 10:54:06,982 - -----------------------------------------------------------------
2020-02-27 10:54:06,982 - Job Controller starting...
2020-02-27 10:54:06,986 - Job Controller is Active
2020-02-27 10:54:06,987 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 10:54:06,988 - Job Controller stopping - lost connection to remote server
2020-02-27 10:54:06,988 - -----------------------------------------------------------------
2020-02-27 10:54:14,594 - -----------------------------------------------------------------
2020-02-27 10:54:14,594 - Job Controller starting...
2020-02-27 10:54:14,597 - Job Controller is Active
2020-02-27 10:54:14,599 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 10:54:14,599 - Job Controller stopping - lost connection to remote server
2020-02-27 10:54:14,599 - -----------------------------------------------------------------
2020-02-27 10:59:12,080 - -----------------------------------------------------------------
2020-02-27 10:59:12,080 - Job Controller starting...
2020-02-27 10:59:12,082 - Job Controller is Active
2020-02-27 10:59:12,084 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_string())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 327, in pop_string
    string_len = self.pop_ulong()
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 258, in pop_ulong
    return struct.unpack_from('Q', self.data, self.offset - 8)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 10:59:12,084 - Job Controller stopping - lost connection to remote server
2020-02-27 10:59:12,084 - -----------------------------------------------------------------
2020-02-27 11:00:12,272 - -----------------------------------------------------------------
2020-02-27 11:00:12,272 - Job Controller starting...
2020-02-27 11:00:12,274 - Job Controller is Active
2020-02-27 11:00:12,275 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    print(msg.pop_uint())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 226, in pop_uint
    return struct.unpack_from('I', self.data, self.offset - 4)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 11:00:12,275 - Job Controller stopping - lost connection to remote server
2020-02-27 11:00:12,275 - -----------------------------------------------------------------
2020-02-27 11:00:33,203 - -----------------------------------------------------------------
2020-02-27 11:00:33,203 - Job Controller starting...
2020-02-27 11:00:33,205 - Job Controller is Active
2020-02-27 11:00:33,207 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    logging.info(msg.pop_uint())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 226, in pop_uint
    return struct.unpack_from('I', self.data, self.offset - 4)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 11:00:33,208 - Job Controller stopping - lost connection to remote server
2020-02-27 11:00:33,208 - -----------------------------------------------------------------
2020-02-27 11:01:02,253 - -----------------------------------------------------------------
2020-02-27 11:01:02,253 - Job Controller starting...
2020-02-27 11:01:02,256 - Job Controller is Active
2020-02-27 11:01:28,007 - -----------------------------------------------------------------
2020-02-27 11:01:28,007 - Job Controller starting...
2020-02-27 11:01:28,011 - Job Controller is Active
2020-02-27 11:01:28,013 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    logging.info(msg.pop_uint())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 226, in pop_uint
    return struct.unpack_from('I', self.data, self.offset - 4)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 11:01:28,014 - Job Controller stopping - lost connection to remote server
2020-02-27 11:01:28,014 - -----------------------------------------------------------------
2020-02-27 11:02:28,195 - -----------------------------------------------------------------
2020-02-27 11:02:28,196 - Job Controller starting...
2020-02-27 11:02:28,198 - Job Controller is Active
2020-02-27 11:02:28,199 - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<JobController.recv_handler() done, defined at /home/lewis/Projects/gwcloud_job_client/core/job_controller.py:350> exception=TypeError("a bytes-like object is required, not 'str'")>
Traceback (most recent call last):
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 361, in recv_handler
    await self.handle_message(message)
  File "/home/lewis/Projects/gwcloud_job_client/core/job_controller.py", line 115, in handle_message
    logging.info(msg.pop_uint())
  File "/home/lewis/Projects/gwcloud_job_client/core/messaging/message.py", line 226, in pop_uint
    return struct.unpack_from('I', self.data, self.offset - 4)[0]
TypeError: a bytes-like object is required, not 'str'
2020-02-27 11:02:28,200 - Job Controller stopping - lost connection to remote server
2020-02-27 11:02:28,200 - -----------------------------------------------------------------
2020-02-27 11:02:51,683 - -----------------------------------------------------------------
2020-02-27 11:02:51,683 - Job Controller starting...
2020-02-27 11:02:51,687 - Job Controller is Active
2020-02-27 11:02:51,688 - 0
2020-02-27 11:02:51,688 - Done
2020-02-27 11:03:17,196 - -----------------------------------------------------------------
2020-02-27 11:03:17,196 - Job Controller starting...
2020-02-27 11:03:17,199 - Job Controller is Active
2020-02-27 11:03:17,200 - 1234
2020-02-27 11:03:17,200 - Done
2020-02-27 11:03:54,591 - -----------------------------------------------------------------
2020-02-27 11:03:54,591 - Job Controller starting...
2020-02-27 11:03:54,594 - Job Controller is Active
2020-02-27 11:03:54,595 - 1234
2020-02-27 11:03:54,595 - Hello there :)
2020-02-27 11:03:54,595 - Done
